// Cross-language RNG parity: the C# mulberry32 must produce bit-identical
// values to the TS engine's src/engine/rng.ts for the same seed — the
// foundation of "identical (seed, action sequence) ⇒ byte-identical states"
// across both engines.
//
// Reference values generated by running the TS nextRandom in Node
// (toPrecision(17) round-trips IEEE doubles exactly).

using Breakthrough.Engine;
using Xunit;

namespace Breakthrough.Engine.Tests;

public class RngParityTests
{
    [Fact]
    public void NextRandom_MatchesTsMulberry32_Seed42()
    {
        double[] expected =
        [
            0.60110375192016363,
            0.44829055899754167,
            0.85246579349040985,
            0.66973404143936932,
            0.17481389874592423,
            0.52659254218451679,
            0.27322799433022738,
            0.62474465393461287,
        ];
        int s = 42;
        foreach (double e in expected)
        {
            var r = Rng.NextRandom(s);
            s = r.State;
            Assert.Equal(e, r.Value, 0.0); // exact bit equality
        }
    }

    [Fact]
    public void NextRandom_MatchesTsMulberry32_NegativeSeed()
    {
        double[] expected =
        [
            0.93357118917629123,
            0.29073142679408193,
            0.86535177426412702,
        ];
        int s = -123456789;
        foreach (double e in expected)
        {
            var r = Rng.NextRandom(s);
            s = r.State;
            Assert.Equal(e, r.Value, 0.0);
        }
    }
}
