/**
 * Starter sets, re-expressed against the v1.4 vocabulary (Brief §6 — this is
 * a re-expression, not a copy-paste). Cut restriction types are re-authored
 * as triggered abilities over §5.1 events; cards that could not be faithfully
 * re-expressed are listed in PORTING_NOTES.md and excluded from starter decks
 * pending Ken's call.
 */
import type { CardDefinition } from '../engine';
import { CHOSEN, OPP_DECK_MATCHING_CHOSEN, PATIENCE, SELF_CARDS_PLAYED, SELF_PRIORITY, at, cmp } from './helpers';

// ─── Blue ────────────────────────────────────────────────────────────────────

export const BLUE_STARTER_CARDS: CardDefinition[] = [
  {
    id: 'blue_modus_ponens',
    name: 'Modus Ponens',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'DRAW_CARDS', value: 1 },
      { type: 'CREATE_TOKEN', tokenDefinitionId: 'logical_chain', count: 1 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Draw a card. Create a Logical Chain.',
    longDescription:
      'If the premise holds, the conclusion follows. A clean line of deduction that builds your case and keeps your hand full.',
  },
  {
    id: 'blue_modus_tollens',
    name: 'Modus Tollens',
    cost: 4,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -2 },
      { type: 'CREATE_TOKEN', tokenDefinitionId: 'logical_chain', count: 2 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 2 Patience. Create two Logical Chains.',
    longDescription: 'Deny the conclusion and the premise crumbles. Two chains of reasoning emerge from a single contradiction.',
  },
  {
    id: 'blue_anticipation',
    name: 'Anticipation',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_DRAW', target: 'self', expiry: at('PLAYER_TURN_END') },
      },
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_SHIELD_BREAK', target: 'self', expiry: at('PLAYER_TURN_END') },
      },
      { type: 'DESTROY_TOKENS', count: 2 },
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_SHIELD_BREAK', target: 'opponent', expiry: at('PLAYER_TURN_START') },
      },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText:
      'Pay 1 Patience. You can’t draw or break shields this turn. Destroy 2 tokens. Your shields can’t be broken until your next turn.',
    longDescription:
      'Sacrifice your current momentum for an ironclad position. The tokens you destroy fuel a wall that protects you through the opponent’s turn.',
  },
  {
    id: 'blue_decisive_punchline',
    name: 'Decisive Punchline',
    cost: 6,
    keywords: [],
    effects: [{ type: 'DESTROY_TOKENS', count: 3 }],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Destroy 3 tokens you control.',
    longDescription:
      'Everything you’ve built leads to this moment. Sacrifice your chains of reasoning for a devastating cascade of leave-triggers.',
  },
  {
    id: 'blue_debunk',
    name: 'Debunk',
    cost: 5,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -3 },
      { type: 'DESTROY_IMPRESSION', owner: 'opponent' },
      { type: 'CREATE_TOKEN', tokenDefinitionId: 'logical_chain', count: 1 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 3 Patience. Destroy an opponent Impression. Create a Logical Chain.',
    longDescription: 'Tear apart a false premise and replace it with cold reason. The destroyed impression fuels a new chain of logic.',
  },
  {
    id: 'blue_powerful_clarity',
    name: 'Powerful Clarity',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'MODIFY_PRIORITY', value: 6 },
      { type: 'CREATE_TOKEN', tokenDefinitionId: 'logical_chain', count: 1 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: '+6 Priority. Create a Logical Chain.',
    longDescription: 'A flash of insight that seizes the conversation and crystallizes into a tangible line of reasoning.',
  },
  {
    id: 'blue_package',
    name: 'Package',
    cost: 1,
    keywords: ['Shield Trigger'],
    effects: [
      { type: 'TRANSFORM_TOKEN', fromTokenId: 'logical_chain', toTokenId: 'impactful_conclusion', count: 1 },
    ],
    shieldTriggerEffects: [
      { type: 'TRANSFORM_TOKEN', fromTokenId: 'logical_chain', toTokenId: 'impactful_conclusion', count: 3, upTo: true },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Transform a Logical Chain into an Impactful Conclusion. Shield Trigger: transform up to 3.',
    longDescription: 'Bundle a chain of reasoning into a devastating conclusion. Under pressure, package even more at once.',
  },
  {
    id: 'blue_hold_attention',
    name: 'Hold Attention',
    cost: 5,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'TRANSFORM_TOKEN', fromTokenId: 'logical_chain', toTokenId: 'captivating_sense', count: 1 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. Transform a Logical Chain into a Captivating Sense.',
    longDescription: 'Weave your logical thread into something that holds their attention, building momentum when it finally releases.',
  },
  {
    id: 'blue_conversational_symmetry',
    name: 'Conversational Symmetry',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'MODIFY_PRIORITY', value: 4 },
      { type: 'TRANSFORM_TOKEN', fromTokenId: 'logical_chain', toTokenId: 'captivating_sense', count: 1 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. +4 Priority. Transform a Logical Chain into a Captivating Sense.',
    longDescription: 'Mirror their energy back at them, transforming raw logic into an irresistible thread of conversation.',
  },
  {
    id: 'blue_timely_follow_up',
    name: 'Timely Follow-up',
    cost: 6,
    keywords: [],
    effects: [
      {
        type: 'APPLY_REPLACEMENT',
        originalTokenId: 'logical_chain',
        replacementTokenId: 'impactful_conclusion',
        expiry: at('PLAYER_TURN_END'),
      },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'This turn, whenever you would create a Logical Chain, create an Impactful Conclusion instead.',
    longDescription: 'Strike while the iron is hot. Every logical thread you spin this turn lands with the full weight of a conclusion.',
  },
  {
    id: 'blue_crystallize',
    name: 'Crystallize',
    cost: 5,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'DESTROY_TOKENS', count: 2 },
      { type: 'CREATE_TOKEN', tokenDefinitionId: 'logical_chain', count: 1 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. Destroy 2 tokens. Create a Logical Chain.',
    longDescription:
      'Collapse two threads of reasoning into a single, refined chain — their leave-triggers fire as you forge something new.',
  },
  {
    id: 'blue_cold_hard_facts',
    name: 'Cold Hard Facts',
    cost: 2,
    keywords: ['Trap'],
    effects: [
      { type: 'TRANSFORM_TOKEN', fromTokenId: 'logical_chain', toTokenId: 'impactful_conclusion', count: 1 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: 'Trap',
    trapTrigger: {
      event: 'CARD_PLAYED',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'CARDS_PLAYED_THIS_TURN', side: 'opponent' }, 'gte', 3),
    },
    effectText: 'Trap: When the enemy plays their 3rd card this turn, transform a Logical Chain into an Impactful Conclusion.',
    longDescription: 'Patience rewards the prepared mind. When they overextend, your reasoning crystallizes into something devastating.',
  },
  {
    id: 'blue_find_fallacy',
    name: 'Find Fallacy',
    cost: 8,
    keywords: ['Trap'],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -2 },
      { type: 'MODIFY_PRIORITY', value: 8 },
    ],
    color: 'Blue',
    supertype: 'Skill',
    subtype: 'Trap',
    trapTrigger: {
      event: 'CARD_PLAYED',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'CARDS_PLAYED_THIS_TURN', side: 'opponent' }, 'gte', 3),
    },
    effectText: 'Trap: When the enemy plays their 3rd card this turn, pay 2 Patience and gain +8 Priority.',
    longDescription: 'Spot the hole in their argument at the perfect moment. Their overconfidence becomes your opening.',
  },
  {
    id: 'blue_eloquence',
    name: 'Eloquence',
    cost: 7,
    keywords: [],
    effects: [{ type: 'MODIFY_PATIENCE', value: -1 }],
    color: 'Blue',
    supertype: 'Skill',
    subtype: 'Impression',
    triggeredAbilities: [
      {
        id: 'eloquence_token_draw',
        trigger: { event: 'TOKEN_DESTROYED', controllerFilter: 'self' },
        effects: [{ type: 'DRAW_CARDS', value: 1 }],
      },
    ],
    effectText: 'Pay 1 Patience. Impression: When a token you control is destroyed, draw a card.',
    longDescription: 'Your eloquent phrasing lingers in the air, ensuring every conclusion you reach opens a new avenue of inquiry.',
  },
  {
    id: 'blue_sophistry',
    name: 'Sophistry',
    cost: 6,
    keywords: [],
    effects: [{ type: 'TRANSFORM_TOKEN', fromTokenId: 'logical_chain', toTokenId: 'impactful_conclusion', all: true }],
    color: 'Blue',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Transform all Logical Chains into Impactful Conclusions.',
    longDescription: 'Dress up every thread of reasoning as an unassailable conclusion. Intellectually dishonest, but devastatingly effective.',
  },
  {
    id: 'blue_lingering_words',
    name: 'Lingering Words',
    cost: 7,
    keywords: [],
    effects: [{ type: 'MODIFY_PATIENCE', value: -2 }],
    color: 'Blue',
    supertype: 'Skill',
    subtype: 'Impression',
    triggeredAbilities: [
      {
        id: 'lingering_words_token_create',
        trigger: { event: 'TOKEN_DESTROYED', controllerFilter: 'self' },
        effects: [{ type: 'CREATE_TOKEN', tokenDefinitionId: 'logical_chain', count: 1 }],
      },
    ],
    effectText: 'Pay 2 Patience. Impression: When a token you control is destroyed, create a Logical Chain.',
    longDescription: 'Your words echo in their mind. Every conclusion that lands spawns a new thread of reasoning to pursue.',
  },
];

// ─── Red ─────────────────────────────────────────────────────────────────────

export const RED_STARTER_CARDS: CardDefinition[] = [
  {
    id: 'red_baleful_shout',
    name: 'Baleful Shout',
    cost: 1,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -3 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 3 },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 3 Patience. Break 3 Guard Shields.',
    longDescription: 'The room goes quiet. Three arguments collapse under the weight of a single, undeniable roar of authority.',
  },
  {
    id: 'red_violent_intent',
    name: 'Violent Intent',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -3 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 1 },
      { type: 'DRAW_CARDS', value: 1 },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 3 Patience. Break 1 Guard Shield. Draw a card.',
    longDescription:
      'Make your intentions unmistakably clear. One defense crumbles, and the shock of it opens your next angle of attack.',
  },
  {
    id: 'red_exude_authority',
    name: 'Exude Authority',
    cost: 1,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'DRAW_CARDS', value: 1 },
      { type: 'MODIFY_PRIORITY', value: 1 },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. Draw a card. +1 Priority.',
    longDescription: 'A subtle shift in posture, a measured look. You need say almost nothing — the room does the work for you.',
  },
  {
    id: 'red_rally',
    name: 'Rally',
    cost: 5,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -2 },
      { type: 'MODIFY_PATIENCE', value: 3 },
      { type: 'DRAW_CARDS', value: 2 },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 2 Patience, then restore 3 Patience. Draw 2 cards.',
    longDescription: 'Pull back, regroup, breathe. The interrogation is a marathon, not a sprint — and you just found your second wind.',
  },
  {
    id: 'red_reframed_perspective',
    name: 'Reframed Perspective',
    cost: 3,
    keywords: ['Trap'],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'MODIFY_PATIENCE', value: 3 },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: 'Trap',
    trapTrigger: {
      event: 'CARD_PLAYED',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'CARDS_PLAYED_THIS_TURN', side: 'opponent' }, 'gte', 2),
    },
    effectText: 'Trap: When the enemy plays their 2nd card this turn, restore 3 Patience (net +2).',
    longDescription:
      'Let them overcommit. When they exhaust their second line of attack, you reframe the entire conversation from a position of calm.',
  },
  {
    id: 'red_press_the_attack',
    name: 'Press the Attack',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -4 },
      { type: 'MODIFY_PRIORITY', value: 4, condition: cmp(PATIENCE, 'lt', 5) },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 4 Patience. If Patience is below 5, +4 Priority.',
    longDescription:
      'The encounter is slipping away — time to throw everything at it. Desperation becomes momentum when you refuse to back down.',
  },
  {
    id: 'red_charismatic_conviction',
    name: 'Charismatic Conviction',
    cost: 5,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 1 },
      { type: 'MODIFY_PATIENCE', value: 3 },
      { type: 'MODIFY_PRIORITY', value: 3, condition: cmp(PATIENCE, 'lt', 7) },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. Break 1 Guard Shield. Restore 3 Patience. If Patience is below 7, +3 Priority.',
    longDescription: 'Tear one wall down, rebuild your composure, then press harder. Under pressure, your conviction is its own argument.',
  },
  {
    id: 'red_gravitas',
    name: 'Gravitas',
    cost: 5,
    keywords: [],
    effects: [{ type: 'MODIFY_PATIENCE', value: -2 }],
    color: 'Red',
    supertype: 'Skill',
    subtype: 'Impression',
    triggeredAbilities: [
      {
        id: 'gravitas_shield_break_priority',
        trigger: { event: 'SHIELD_BROKEN', controllerFilter: 'self' },
        effects: [{ type: 'MODIFY_PRIORITY', value: 1 }],
      },
    ],
    effectText: 'Pay 2 Patience. Impression: Whenever you break a shield, +1 Priority.',
    longDescription: 'Your presence becomes the argument. Each defense you shatter earns you a moment longer in control of the room.',
  },
  {
    id: 'red_overwhelming_onslaught',
    name: 'Overwhelming Onslaught',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 1, scale: SELF_CARDS_PLAYED },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. Break 1 Guard Shield for each card you’ve played this turn (including this one).',
    longDescription: 'Each word lands harder than the last. Your momentum becomes a battering ram.',
  },
  {
    id: 'red_magnetic_rhetoric',
    name: 'Magnetic Rhetoric',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'MODIFY_PATIENCE', value: 1, scale: SELF_CARDS_PLAYED },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. Restore 1 Patience for each card played this turn (including this one).',
    longDescription: 'The longer you’ve been talking, the more persuasive you become. Your argument builds on itself.',
  },
  {
    id: 'red_passionate_persuasion',
    name: 'Passionate Persuasion',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -2 },
      { type: 'MODIFY_PATIENCE', value: 1, scale: SELF_PRIORITY },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 2 Patience. Restore 1 Patience for each Priority point remaining after playing this card.',
    longDescription: 'Raw conviction poured into every word. The more momentum you carry, the harder you hit.',
  },
  {
    id: 'red_vindication',
    name: 'Vindication',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'MODIFY_PRIORITY', value: 1, scale: { kind: 'OPP_SHIELDS_BROKEN_BY_PLAYER_PREV_TURN' } },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. +1 Priority for each opponent shield you broke last turn.',
    longDescription: 'Yesterday’s victories become today’s fuel. Every defense you dismantled hands you another opening.',
  },
  {
    id: 'red_submit',
    name: 'Submit',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -1 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 1, scale: { kind: 'MISSING_PATIENCE' } },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience. Break X Guard Shields, where X is how far Patience has fallen below its start.',
    longDescription: 'The cracks are already showing. You press into every gap their exhaustion has left open.',
  },
  {
    id: 'red_commanding_aura',
    name: 'Commanding Aura',
    cost: 3,
    keywords: [],
    effects: [
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_PATIENCE_GAIN', target: 'both', expiry: at('PLAYER_TURN_START', 3) },
      },
    ],
    color: 'Red',
    supertype: 'Skill',
    subtype: 'Impression',
    triggeredAbilities: [
      {
        id: 'ca_bonus_break',
        trigger: { event: 'SHIELD_BROKEN', controllerFilter: 'self' },
        maxTimesPerPlay: 1,
        effects: [{ type: 'BREAK_SHIELDS', target: 'opponent', count: 1 }],
      },
    ],
    effectText: 'Impression: Prevent all Patience gains for 3 turns. Once per play: when you break a shield, break one more.',
    longDescription: 'Your authority fills the room. Every attack lands harder and their attempts to recover fall flat.',
  },
  {
    id: 'red_ultimatum',
    name: 'Ultimatum',
    cost: 2,
    keywords: ['Trap'],
    effects: [{ type: 'MODIFY_PATIENCE', value: -1 }],
    color: 'Red',
    supertype: 'Skill',
    subtype: 'Trap',
    trapTrigger: { event: 'CARD_PLAYED', controllerFilter: 'opponent' },
    trapPersistent: true,
    effectText: 'Trap — persistent. Each time your opponent plays a card, pay 1 Patience. Expires at your next turn start.',
    longDescription: 'You’ve laid your terms and you’re not moving. Every word they speak digs them deeper.',
  },
  {
    id: 'red_intimidating_presence',
    name: 'Intimidating Presence',
    cost: 2,
    keywords: [],
    effects: [],
    color: 'Red',
    supertype: 'Skill',
    subtype: 'Impression',
    triggeredAbilities: [
      {
        id: 'ip_npc_play',
        trigger: { event: 'CARD_PLAYED', controllerFilter: 'opponent' },
        maxTimesPerTurn: 1,
        effects: [{ type: 'MODIFY_PATIENCE', value: -1 }],
      },
    ],
    effectText: 'Impression: Once per turn, when your opponent plays a card, pay 1 Patience.',
    longDescription: 'You don’t need to move. The weight of your presence makes every action they take cost them something.',
  },
];

// ─── Green ───────────────────────────────────────────────────────────────────

export const GREEN_STARTER_CARDS: CardDefinition[] = [
  {
    id: 'green_listening_ear',
    name: 'Listening Ear',
    cost: 0,
    keywords: [],
    effects: [{ type: 'MODIFY_PATIENCE', value: 3 }],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Restore 3 Patience.',
    longDescription: 'Sometimes the most powerful thing you can do is simply listen. Your attentive silence puts them at ease.',
  },
  {
    id: 'green_rally',
    name: 'Rally',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: 3 },
      { type: 'DRAW_CARDS', value: 2 },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Restore 3 Patience. Draw 2 cards.',
    longDescription: 'A reassuring word, a moment of calm — your composure steadies everything around you.',
  },
  {
    id: 'green_emotional_connection',
    name: 'Emotional Connection',
    cost: 0,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: 2 },
      { type: 'REVEAL_NPC_HAND' },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Restore 2 Patience. The opponent reveals their hand.',
    longDescription: 'You reach them on a level that has nothing to do with facts. For a moment, their guard drops entirely.',
  },
  {
    id: 'green_deep_understanding',
    name: 'Deep Understanding',
    cost: 0,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: 3 },
      { type: 'DECK_REVEAL', side: 'opponent', count: 3 },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Restore 3 Patience. Look at the top 3 cards of the opponent’s deck.',
    longDescription: 'Your empathy runs so deep you can sense what they’re about to say before they say it.',
  },
  {
    id: 'green_display_of_benevolence',
    name: 'Display of Benevolence',
    cost: 2,
    keywords: [],
    effects: [{ type: 'MODIFY_PATIENCE', value: 10, altValue: 15, altCondition: cmp(PATIENCE, 'lt', 10) }],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Restore 10 Patience. If Patience is below 10, restore 15 instead.',
    longDescription: 'An act of genuine kindness — no strings attached. When things are at their worst, your generosity overwhelms.',
  },
  {
    id: 'green_empathy',
    name: 'Empathy',
    cost: 3,
    keywords: ['Rapport'],
    rapport: { min: 1, max: 10, checked: { kind: 'STAGED_CARD_COST' } },
    effects: [
      { type: 'COPY_FROM_NPC_DECK', count: 1, costEquals: CHOSEN, patienceCostOverride: CHOSEN },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText:
      '{Rapport} Choose a number 1–10. Copy an opponent-deck card with that Priority cost into your hand. It costs that much Patience to play.',
    longDescription: 'You understand them so completely that you can mirror their thoughts. Their strategy becomes your own.',
  },
  {
    id: 'green_keeping_an_open_mind',
    name: 'Keeping an Open Mind',
    cost: 2,
    keywords: ['Rapport'],
    rapport: { min: 1, max: 10, checked: OPP_DECK_MATCHING_CHOSEN },
    effects: [
      { type: 'REVEAL_NPC_DECK_TOP' },
      {
        type: 'DRAW_CARDS',
        value: 1,
        scale: OPP_DECK_MATCHING_CHOSEN,
        condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'gte', 1),
      },
      {
        type: 'INCREMENT_COUNTERS',
        counterName: 'rapport',
        targetDefinitionId: 'green_to_truly_know',
        amount: 1,
        condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'gte', 1),
      },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: 'Impression',
    leaveTriggerEffects: [{ type: 'HIDE_NPC_DECK_TOP' }],
    effectText:
      'The opponent plays with the top card of their deck revealed. {Rapport} Choose 1–10. If the opponent’s deck holds cards with that cost, draw that many.',
    longDescription: 'Stay open to what they’re showing you. The more you understand their rhythm, the more ammunition you find.',
  },
  {
    id: 'green_engaging_insight',
    name: 'Engaging Insight',
    cost: 2,
    keywords: ['Rapport'],
    rapport: { min: 1, max: 10, checked: OPP_DECK_MATCHING_CHOSEN },
    effects: [
      {
        type: 'MODIFY_PATIENCE',
        value: 3,
        scale: OPP_DECK_MATCHING_CHOSEN,
        condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'gte', 1),
      },
      {
        type: 'INCREMENT_COUNTERS',
        counterName: 'rapport',
        targetDefinitionId: 'green_to_truly_know',
        amount: 1,
        condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'gte', 1),
      },
      { type: 'MODIFY_PATIENCE', value: -5, condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'lt', 1) },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText: '{Rapport} Choose 1–10. If the opponent’s deck holds cards with that cost, restore 3 Patience per match. Otherwise pay 5 Patience.',
    longDescription: 'A calculated read on their psyche. Get it right, and everything flows. Get it wrong, and the rapport backfires.',
  },
  {
    id: 'green_like_an_open_book',
    name: 'Like an Open Book',
    cost: 3,
    keywords: ['Rapport'],
    rapport: { min: 1, max: 10, checked: OPP_DECK_MATCHING_CHOSEN },
    effects: [
      {
        type: 'MODIFY_PATIENCE',
        value: 5,
        scale: OPP_DECK_MATCHING_CHOSEN,
        condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'gte', 2),
      },
      {
        type: 'INCREMENT_COUNTERS',
        counterName: 'rapport',
        targetDefinitionId: 'green_to_truly_know',
        amount: 1,
        condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'gte', 2),
      },
      { type: 'MODIFY_PATIENCE', value: -10, condition: cmp(OPP_DECK_MATCHING_CHOSEN, 'lt', 2) },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText: '{Rapport} Choose 1–10. If the opponent’s deck holds 2+ cards with that cost, restore 5 Patience per match. Otherwise pay 10 Patience.',
    longDescription: 'You can read them like a book. But overconfidence is its own trap — miss, and they close off harder than before.',
  },
  {
    id: 'green_sensitive_deflection',
    name: 'Sensitive Deflection',
    cost: 2,
    keywords: ['Trap'],
    effects: [
      {
        type: 'PLACE_SHIELDS',
        target: 'self',
        count: 3,
        condition: cmp({ kind: 'PLAYER_SHIELDS_BROKEN_BY_NPC_THIS_TURN' }, 'gte', 2),
      },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: 'Trap',
    // Old trigger OPPONENT_BREAKS_SHIELD was never dispatched (Brief §6.3) —
    // re-authored onto the canonical SHIELD_BROKEN event.
    trapTrigger: {
      event: 'SHIELD_BROKEN',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'PLAYER_SHIELDS_BROKEN_BY_NPC_THIS_TURN' }, 'gte', 2),
    },
    effectText: 'Trap: When the opponent breaks their 2nd shield of yours this turn, place 3 Placeholder Shields.',
    longDescription: 'When they push too hard, you softly redirect. Three new walls rise as naturally as a change of subject.',
  },
  {
    id: 'green_disarming_word',
    name: 'Disarming Word',
    cost: 2,
    keywords: ['Rapport', 'Trap'],
    rapport: { min: 1, max: 10, checked: { kind: 'STAGED_CARD_COST' } },
    effects: [
      { type: 'CANCEL_STAGED_CARD' },
      { type: 'MODIFY_PATIENCE', value: 1, scale: CHOSEN },
      { type: 'INCREMENT_COUNTERS', counterName: 'rapport', targetDefinitionId: 'green_to_truly_know', amount: 1 },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: 'Trap',
    // Old cancel implementation didn't prevent resolution (Brief §6.5) —
    // ported onto the CARD_STAGED window and tested to genuinely cancel.
    trapTrigger: {
      event: 'CARD_STAGED',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'STAGED_CARD_COST' }, 'eq', CHOSEN),
    },
    effectText: '{Rapport} Trap: Choose 1–10. If the opponent stages a card with that cost, cancel it and restore that much Patience.',
    longDescription: 'A single well-placed word, spoken at just the right moment, and their entire argument unravels before it begins.',
  },
  {
    id: 'green_i_know_how_you_feel',
    name: 'I Know How You Feel',
    cost: 2,
    keywords: [],
    effects: [{ type: 'REVEAL_NPC_HAND' }],
    color: 'Green',
    supertype: 'Skill',
    subtype: 'Impression',
    impressionDuration: { turns: 2, returnToDeck: true },
    leaveTriggerEffects: [{ type: 'HIDE_NPC_HAND' }],
    effectText: 'The opponent plays with their hand revealed. Shuffles back into your deck after 2 of your turns.',
    longDescription:
      'You see right through them — every card on the table, every move they’re planning. But the clarity won’t last forever.',
  },
  {
    id: 'green_shared_perspective',
    name: 'Shared Perspective',
    cost: 5,
    keywords: ['Rapport'],
    rapport: { min: 1, max: 10, checked: { kind: 'STAGED_CARD_COST' } },
    effects: [
      { type: 'COPY_FROM_NPC_DECK', count: 2, costEquals: CHOSEN, withShieldBreak: true, patienceCostOverride: CHOSEN },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: null,
    effectText:
      '{Rapport} Choose 1–10. Copy two opponent-deck cards with that cost and a shield-break effect. They cost that much Patience to play.',
    longDescription: 'You don’t just understand them — you think like them. Their best weapons become yours, wielded with ruthless precision.',
  },
  {
    id: 'green_genuine_enjoyment',
    name: 'Genuine Enjoyment',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'MODIFY_PATIENCE', value: -5 },
      { type: 'APPLY_RESTRICTION', restriction: { type: 'PREVENT_SHIELD_BREAK', target: 'opponent' } },
    ],
    color: 'Green',
    supertype: 'Skill',
    subtype: 'Impression',
    impressionDestroyBelowPatience: 15,
    // Ken (v1.4.1): not prevention-with-cost — plain PREVENT_SHIELD_BREAK
    // (linked to this Impression) plus a Patience drain.
    effectText:
      'Pay 5 Patience. While this Impression is on the Field, the opponent cannot break shields. Destroyed if Patience falls below 15.',
    longDescription: 'Your warmth is disarming. They can’t bring themselves to push too hard — but only as long as you keep smiling.',
  },
  {
    id: 'green_to_truly_know',
    name: 'To Truly Know',
    cost: 2,
    keywords: [],
    effects: [],
    color: 'Green',
    supertype: 'Skill',
    subtype: 'Impression',
    impressionDestroyBelowPatience: 10,
    // Ken (v1.4.1): the secondary effect fires at the start of the player's
    // turn; it checks the count of the counters on itself to decide its tier.
    turnStartEffects: [
      {
        type: 'BREAK_SHIELDS',
        target: 'opponent',
        count: 10,
        condition: cmp({ kind: 'COUNTER', counterName: 'rapport', permanentDefId: 'self' }, 'gte', 10),
      },
      {
        type: 'BREAK_SHIELDS',
        target: 'opponent',
        count: 5,
        condition: {
          all: [
            cmp({ kind: 'COUNTER', counterName: 'rapport', permanentDefId: 'self' }, 'gte', 5),
            cmp({ kind: 'COUNTER', counterName: 'rapport', permanentDefId: 'self' }, 'lt', 10),
          ],
        },
      },
      {
        type: 'BREAK_SHIELDS',
        target: 'opponent',
        count: 3,
        condition: {
          all: [
            cmp({ kind: 'COUNTER', counterName: 'rapport', permanentDefId: 'self' }, 'gte', 3),
            cmp({ kind: 'COUNTER', counterName: 'rapport', permanentDefId: 'self' }, 'lt', 5),
          ],
        },
      },
    ],
    effectText:
      'Rapport successes place counters here. At the start of your turn: 3+ counters break 3 Guard Shields, 5+ break 5, 10+ break 10. Destroyed if Patience falls below 10.',
    longDescription: 'True understanding takes time. Each insight builds on the last until their every defense is laid bare.',
  },
];

// ─── Orange ──────────────────────────────────────────────────────────────────

export const ORANGE_STARTER_CARDS: CardDefinition[] = [
  {
    id: 'orange_appeal_to_authority',
    name: 'Appeal to Authority',
    cost: 2,
    keywords: [],
    effects: [
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_SHIELD_BREAK', target: 'self', expiry: at('PLAYER_TURN_END', 2) },
      },
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_SHIELD_BREAK', target: 'opponent', expiry: at('PLAYER_TURN_END', 2) },
      },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Until the end of your next turn, no shields can be broken.',
    longDescription:
      'You invoke a higher power — a regulation, a precedent, an unimpeachable name. For a moment, both sides are frozen in place.',
  },
  {
    id: 'orange_by_the_law',
    name: 'By the Law',
    cost: 3,
    keywords: ['Heavy Hand'],
    effects: [{ type: 'MODIFY_PRIORITY', value: -2, target: 'opponent' }],
    heavyHandEffects: [
      { type: 'MODIFY_PRIORITY', value: -2, target: 'opponent' },
      { type: 'BREAK_SHIELDS', target: 'self', count: 1 },
    ],
    returnToDeck: true,
    color: 'Orange',
    supertype: 'Skill',
    subtype: null,
    effectText:
      'Normal: −2 opponent Priority. Heavy Hand (double cost): also break one of your own shields. Shuffles back into your deck after use.',
    longDescription:
      'The law is a blunt instrument. Swing it lightly, and it nudges. Swing it hard, and something breaks — maybe even something of yours.',
  },
  {
    id: 'orange_exacting_decree',
    name: 'Exacting Decree',
    cost: 3,
    keywords: ['Heavy Hand'],
    effects: [
      { type: 'APPLY_RESTRICTION', restriction: { type: 'INCREASE_CARD_COST', target: 'both', value: 1 } },
    ],
    heavyHandEffects: [
      { type: 'APPLY_RESTRICTION', restriction: { type: 'INCREASE_CARD_COST', target: 'both', value: 2 } },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Impression',
    effectText:
      'Normal: all cards cost +1 Priority (both sides). Heavy Hand (double cost): +2 instead. Lasts while this Impression is on the Field.',
    longDescription: 'A decree from on high. Every word now carries a surcharge, every argument an added toll. The bureaucracy has arrived.',
  },
  {
    id: 'orange_mind_tax',
    name: 'Mind Tax',
    cost: 2,
    keywords: [],
    effects: [],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Impression',
    impressionDuration: { turns: 2 },
    // v1.4.1: CARD_DRAWN canonical event — the tax reacts per extra draw.
    triggeredAbilities: [
      {
        id: 'mind_tax_per_draw',
        trigger: {
          event: 'CARD_DRAWN',
          controllerFilter: 'opponent',
          condition: cmp({ kind: 'EVENT_IS_EXTRA_DRAW' }, 'eq', 1),
        },
        effects: [{ type: 'MODIFY_PRIORITY', value: 1 }],
      },
    ],
    effectText:
      'Impression (2 turns): gain 1 Priority whenever the opponent draws an extra card. (Heavy Hand variant pending — see porting notes.)',
    longDescription: 'You plant a seed of suspicion. Every new piece of information the witness reaches for now costs them credibility.',
  },
  {
    id: 'orange_cognitive_burden',
    name: 'Cognitive Burden',
    cost: 2,
    keywords: [],
    effects: [
      { type: 'APPLY_RESTRICTION', restriction: { type: 'MAX_TURN_START_DRAW', target: 'both', value: 3 } },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Impression',
    effectText: 'Both sides may only draw up to 3 cards at the start of each turn. Lasts while this Impression is on the Field.',
    longDescription: 'The weight of what has been said settles over both sides. Thoughts come slower now, each one heavier than the last.',
  },
  {
    id: 'orange_strict_compliance',
    name: 'Strict Compliance',
    cost: 5,
    keywords: [],
    effects: [
      { type: 'APPLY_RESTRICTION', restriction: { type: 'MAX_PLAYS_PER_TURN', target: 'both', value: 2 } },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Impression',
    effectText: 'Both sides may only play up to 2 cards per turn. Lasts while this Impression is on the Field.',
    longDescription: 'The rules are clear. Two statements, no more. Anything beyond that is out of order.',
  },
  {
    id: 'orange_fair_provision',
    name: 'Fair Provision',
    cost: 3,
    keywords: ['Trap'],
    effects: [{ type: 'MODIFY_PATIENCE', value: 2 }],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Trap',
    trapPersistent: true,
    // Re-authored (old PATIENCE_PER_OPPONENT_CARD restriction was cut): a
    // persistent trap covering the opponent's next turn.
    trapTrigger: { event: 'CARD_PLAYED', controllerFilter: 'opponent' },
    effectText: 'Trap — persistent: restore 2 Patience each time the opponent plays a card. Expires at your next turn start.',
    longDescription: 'You establish a principle of fairness. Every word they speak now strengthens your position.',
  },
  {
    id: 'orange_equal_ground',
    name: 'Equal Ground',
    cost: 4,
    keywords: [],
    effects: [
      { type: 'APPLY_RESTRICTION', restriction: { type: 'PRIORITY_FLOOR', target: 'self', value: -3 } },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Impression',
    effectText: 'While this Impression is on the Field, your Priority cannot drop below −3.',
    longDescription: 'You draw a line in the sand. No matter how hard they push, there is a floor beneath you.',
  },
  {
    id: 'orange_gross_oversight',
    name: 'Gross Oversight',
    cost: 2,
    keywords: ['Trap'],
    effects: [
      { type: 'CANCEL_STAGED_CARD' },
      { type: 'MODIFY_PATIENCE', value: 1, scale: { kind: 'STAGED_CARD_BREAK_COUNT' } },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Trap',
    // Old intercept was broken (Brief §6.5) — ported onto CARD_STAGED and
    // tested to genuinely cancel.
    trapTrigger: {
      event: 'CARD_STAGED',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'STAGED_CARD_BREAK_COUNT' }, 'gte', 1),
    },
    effectText:
      'Trap: When the opponent stages a card that would break shields, cancel it and restore 1 Patience per prevented break.',
    longDescription: 'You spot the flaw in their argument before it lands. The attack crumbles, and you feel vindicated.',
  },
  {
    id: 'orange_artful_injunction',
    name: 'Artful Injunction',
    cost: 3,
    keywords: [],
    effects: [
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_EXTRA_DRAWS', target: 'opponent', expiry: at('PLAYER_TURN_END', 2) },
      },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Until the end of your next turn, the opponent cannot draw extra cards. (Priority-per-blocked-draw rider pending — see porting notes.)',
    longDescription: 'You file an injunction. The witness may speak, but they may not reach for new material.',
  },
  {
    id: 'orange_semantic_quagmire',
    name: 'Semantic Quagmire',
    cost: 3,
    keywords: ['Trap'],
    effects: [
      { type: 'MODIFY_PRIORITY', value: 5 },
      {
        type: 'SCHEDULE_EFFECTS',
        effects: [{ type: 'MODIFY_PRIORITY', value: 3 }],
        at: at('PLAYER_TURN_START'),
      },
    ],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Trap',
    // Old COMPOUND_NPC_TURN trigger re-expressed as NPC_TURN_END + a compound
    // condition over the §4-named per-turn counters.
    trapTrigger: {
      event: 'NPC_TURN_END',
      condition: {
        all: [
          cmp({ kind: 'EXTRA_DRAWS_THIS_TURN', side: 'opponent' }, 'gte', 1),
          cmp({ kind: 'PLAYER_SHIELDS_BROKEN_BY_NPC_THIS_TURN' }, 'gte', 1),
          cmp({ kind: 'PRIORITY_GAINED_THIS_TURN', side: 'opponent' }, 'gte', 1),
        ],
      },
    },
    effectText:
      'Trap: At the end of an opponent turn in which they drew extra, broke a shield, and gained Priority — +5 Priority now, +3 more at your next turn start.',
    longDescription: 'The more they do, the deeper they sink. Every action feeds the quagmire.',
  },
  {
    id: 'orange_generous_concession',
    name: 'Generous Concession',
    cost: 2,
    keywords: ['Trap'],
    effects: [{ type: 'MODIFY_PATIENCE', value: 1, scale: { kind: 'EVENT_DELTA_ABS' } }],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Trap',
    trapPersistent: true,
    // Re-authored (old PATIENCE_PER_NPC_PRIORITY_GAIN was cut): persistent
    // trap on PRIORITY_CHANGED, spends only (delta < 0).
    trapTrigger: {
      event: 'PRIORITY_CHANGED',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'EVENT_DELTA' }, 'lt', 0),
    },
    effectText: 'Trap — persistent: restore 1 Patience for every Priority the opponent spends. Expires at your next turn start.',
    longDescription: 'You concede the floor graciously. Their every assertion only makes you more patient.',
  },
  {
    id: 'orange_double_edged_approach',
    name: 'Double-edged Approach',
    cost: 1,
    keywords: ['Trap'],
    effects: [{ type: 'BREAK_SHIELDS', target: 'self', count: 1 }],
    color: 'Orange',
    supertype: 'Skill',
    subtype: 'Trap',
    trapPersistent: true,
    // Re-authored (old SELF_BREAK_ON_NPC_SHIELD_BREAK was cut): persistent
    // trap on SHIELD_BROKEN filtered to breaks of the trap owner's shields.
    trapTrigger: {
      event: 'SHIELD_BROKEN',
      controllerFilter: 'opponent',
      condition: cmp({ kind: 'EVENT_IS_OWN_SHIELD' }, 'eq', 1),
    },
    effectText: 'Trap — persistent: when the opponent breaks one of your shields, break an additional one of your own.',
    longDescription: 'You lean into the blow. The pain doubles, but so does the resolve.',
  },
];
