/**
 * Fan Club President set — re-expressed per Brief §6.2: all devotion logic is
 * generic counters/thresholds/amplifiers in card data. The engine does not
 * know these cards exist.
 */
import type { CardDefinition } from '../engine';
import { at, cmp } from './helpers';

export const FCP_CARDS: CardDefinition[] = [
  {
    id: 'fcp_youre_a_hindrance',
    name: "You're a Hindrance",
    cost: 4,
    keywords: [],
    effects: [{ type: 'MODIFY_PATIENCE', value: -5 }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Drain 5 Patience.',
    longDescription: 'The fan sees you as nothing but an obstacle between them and their idol.',
  },
  {
    id: 'fcp_panicked_memories',
    name: 'Panicked Memories',
    cost: 0,
    keywords: ['Shield Trigger'],
    effects: [],
    shieldTriggerEffects: [{ type: 'MODIFY_PATIENCE', value: -3 }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Shield Trigger: drain 3 Patience.',
    longDescription: 'Disturbing recollections surface when defenses are broken.',
  },
  {
    id: 'fcp_moment_of_clarity',
    name: 'Moment of Clarity',
    cost: 0,
    keywords: ['Shield Trigger'],
    effects: [],
    shieldTriggerEffects: [{ type: 'MODIFY_PATIENCE', value: 5 }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Shield Trigger: restore 5 Patience.',
    longDescription: 'A fleeting instant of lucidity breaks through the obsession.',
  },
  {
    id: 'fcp_idols_favor',
    name: "Idol's Favor",
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: 'Impression',
    thresholds: [
      {
        counterName: 'devotion',
        value: 10,
        consume: true,
        effects: [
          { type: 'BREAK_SHIELDS', target: 'opponent', count: 3 }, // NPC → player shields
          { type: 'BREAK_SHIELDS', target: 'self', count: 3 }, // own Guards (§6.6.3)
          { type: 'MODIFY_PATIENCE', value: -3 },
        ],
      },
    ],
    // Old "10 total shields broken" clause has no cumulative counter yet —
    // approximated as all-Guards-broken; flagged in PORTING_NOTES.md.
    transformCondition: {
      condition: cmp({ kind: 'NPC_GUARDS_STANDING' }, 'eq', 0),
      intoDefinitionId: 'fcp_my_idol',
    },
    effectText:
      'Devotion accumulates here. At 10: consume 10 — break 3 shields on both sides, drain 3 Patience. When all Guard Shields are down: transforms into My Idol.',
    longDescription: "The idol's influence radiates outward, growing stronger with every act of devotion.",
  },
  {
    id: 'fcp_my_idol',
    name: 'My Idol',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: 'Impression',
    turnStartEffects: [
      { type: 'MODIFY_PRIORITY', value: 5 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 3 },
      { type: 'MODIFY_PATIENCE', value: -3 },
    ],
    effectText: 'At the start of the fan’s turn: +5 Priority, break 3 of your shields, drain 3 Patience.',
    longDescription: 'The idol takes form — every turn begins with devastation.',
  },
  {
    id: 'fcp_im_his',
    name: "I'm His",
    cost: 2,
    keywords: [],
    effects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 2 },
      { type: 'PLACE_SHIELDS', target: 'self', count: 2 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+2 devotion. Place 2 Guard Shields.',
    longDescription: 'A declaration of possession — the fan stakes their claim and fortifies their resolve.',
  },
  {
    id: 'fcp_blind_loyalty',
    name: 'Blind Loyalty',
    cost: 3,
    keywords: [],
    effects: [{ type: 'PLACE_SHIELDS', target: 'self', count: 4 }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Place 4 Guard Shields.',
    longDescription: 'Unwavering devotion becomes an impenetrable wall of denial.',
  },
  {
    id: 'fcp_he_loves_me',
    name: 'He Loves Me',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 2 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 1 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+2 devotion. Break 1 of your shields.',
    longDescription: "Love is a weapon. The idol's affection leaves scars.",
  },
  {
    id: 'fcp_he_really_loves_me',
    name: 'He Really Loves Me',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 2 },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 2 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+2 devotion. Break 2 of your shields.',
    longDescription: 'Doubled devotion, doubled destruction. The idol is always watching.',
  },
  {
    id: 'fcp_im_never_alone',
    name: "I'm Never Alone",
    cost: 2,
    keywords: [],
    effects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 2 },
      { type: 'DRAW_CARDS', value: 1 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+2 devotion. Draw 1 card.',
    longDescription: 'The presence is always there — in the mirrors, in the silence, in the next card drawn.',
  },
  {
    id: 'fcp_fantasy',
    name: 'FANtasy',
    cost: 3,
    keywords: [],
    effects: [{ type: 'DRAW_CARDS', value: 3 }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Draw 3 cards.',
    longDescription: 'Lost in a world where every fantasy feels real and every reality feels staged.',
  },
  {
    id: 'fcp_complete_devotion',
    name: 'Complete Devotion',
    cost: 2,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: 'Impression',
    counterAmplifiers: [{ counterName: 'devotion', extra: 1 }],
    effectText: 'All devotion gains are amplified: +1 extra per gain.',
    longDescription: 'Total surrender to the cause. Every act of worship echoes louder.',
  },
  {
    id: 'fcp_his_loyal_fan',
    name: 'His Loyal Fan',
    cost: 2,
    keywords: ['Trap'],
    effects: [
      {
        type: 'INCREMENT_COUNTERS',
        counterName: 'devotion',
        targetDefinitionId: 'fcp_idols_favor',
        amount: 1,
        scale: { kind: 'OPP_SHIELDS_BROKEN_BY_PLAYER_THIS_TURN' },
      },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: 'Trap',
    // Old END_OF_PLAYER_TURN trigger was never dispatched (Brief §6.4) —
    // re-authored per printed intent onto the canonical PLAYER_TURN_END.
    trapTrigger: {
      event: 'PLAYER_TURN_END',
      condition: cmp({ kind: 'OPP_SHIELDS_BROKEN_BY_PLAYER_THIS_TURN' }, 'gte', 1),
    },
    effectText: 'Trap: At the end of your turn, +1 devotion per shield you broke that turn.',
    longDescription: "Every attack on the idol only deepens the fan's obsession.",
  },
  {
    id: 'fcp_deranged_witness',
    name: 'Deranged Witness',
    cost: 4,
    keywords: [],
    effects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 4 },
      { type: 'BREAK_SHIELDS', target: 'self', count: 2 },
      { type: 'MODIFY_PATIENCE', value: -3 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+4 devotion. Sacrifice 2 own Guard Shields. Drain 3 Patience.',
    longDescription: 'Sanity crumbles under the weight of devotion. Self-destruction becomes an offering.',
  },
  {
    id: 'fcp_my_only_meaning',
    name: 'My Only Meaning',
    cost: 5,
    keywords: [],
    effects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 10 },
      { type: 'RESHUFFLE_DECK' },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+10 devotion. Reshuffle the discard pile back into the deck.',
    longDescription: 'There is nothing else. No other purpose. Just the idol.',
  },
  {
    id: 'fcp_and_hes_mine',
    name: "And He's Mine",
    cost: 3,
    keywords: [],
    effects: [
      {
        type: 'INCREMENT_COUNTERS',
        counterName: 'devotion',
        targetDefinitionId: 'fcp_idols_favor',
        amount: 1,
        scale: { kind: 'GUARDS_PLACED_BY_NPC_THIS_TURN' },
      },
      { type: 'BREAK_SHIELDS', target: 'opponent', count: 1, scale: { kind: 'GUARDS_PLACED_BY_NPC_THIS_TURN' } },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+1 devotion per Guard Shield placed this turn. Break 1 of your shields per Guard placed.',
    longDescription: 'Possession made manifest. Every wall built becomes a weapon wielded.',
  },
  {
    id: 'fcp_impenetrable_insanity',
    name: 'Impenetrable Insanity',
    cost: 4,
    keywords: [],
    effects: [
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_SHIELD_BREAK', target: 'opponent', expiry: at('PLAYER_TURN_END') },
      },
      {
        type: 'MODIFY_PRIORITY',
        value: 1,
        scale: { kind: 'COUNTER', counterName: 'devotion', permanentDefId: 'fcp_idols_favor' },
      },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'You cannot break shields during your next turn. The fan gains +1 Priority per devotion.',
    longDescription: 'Madness becomes armor. The deeper the obsession, the more unassailable the defenses.',
  },
  {
    id: 'fcp_lunatic_love',
    name: 'Lunatic Love',
    cost: 3,
    keywords: [],
    effects: [
      { type: 'APPLY_RESTRICTION', restriction: { type: 'INCREASE_CARD_COST', target: 'self', value: 1 } },
      { type: 'APPLY_RESTRICTION', restriction: { type: 'PATIENCE_COST_PER_CARD', target: 'self', value: 1 } },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: 'Impression',
    effectText:
      'The fan’s cards cost +1 Priority and drain 1 Patience each. Lasts while this Impression is on the Field. (Devotion-pays-Priority rider pending — see porting notes.)',
    longDescription: 'Love twists into something dangerous — every word they speak costs more, but devotion fuels the fire.',
  },
  {
    id: 'fcp_distracting_madness',
    name: 'Distracting Madness',
    cost: 2,
    keywords: ['Trap'],
    effects: [
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_EXTRA_DRAWS', target: 'opponent', expiry: at('PLAYER_TURN_END') },
      },
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 2 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: 'Trap',
    // Old END_OF_PLAYER_TURN trigger re-authored per printed intent ("prevent
    // opponent extra draws this turn"): fires at PLAYER_TURN_START so the
    // restriction covers that whole player turn (Brief §6.4).
    trapTrigger: { event: 'PLAYER_TURN_START' },
    effectText: 'Trap: At the start of your turn, you cannot draw extra cards that turn. +2 devotion.',
    longDescription: 'Their madness is a distraction — while you struggle to think, their obsession only grows.',
  },
  {
    id: 'fcp_unhinged_focus',
    name: 'Unhinged Focus',
    cost: 3,
    keywords: ['Trap'],
    effects: [
      {
        type: 'APPLY_RESTRICTION',
        restriction: { type: 'PREVENT_PATIENCE_GAIN', target: 'opponent', expiry: at('PLAYER_TURN_END') },
      },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: 'Trap',
    // Re-authored per printed intent, as above (Brief §6.4).
    trapTrigger: { event: 'PLAYER_TURN_START' },
    effectText: 'Trap: At the start of your turn, you cannot restore Patience that turn.',
    longDescription: 'Their focus is absolute, unnervingly so — nothing you say can calm them now.',
  },
  {
    id: 'fcp_youll_never_tear_us_apart',
    name: "You'll Never Tear Us Apart",
    cost: 3,
    keywords: [],
    effects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 2 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: '+2 devotion.',
    longDescription: 'An unshakeable bond — nothing can separate the fan from their idol.',
  },
  {
    id: 'fcp_fans_solace',
    name: "Fan's Solace",
    cost: 0,
    keywords: ['Shield Trigger'],
    effects: [],
    shieldTriggerEffects: [
      { type: 'INCREMENT_COUNTERS', counterName: 'devotion', targetDefinitionId: 'fcp_idols_favor', amount: 5 },
    ],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Shield Trigger: +5 devotion.',
    longDescription: 'Even in defeat, the fan draws comfort from their devotion.',
  },
  {
    id: 'fcp_crippling_fear',
    name: 'Crippling Fear',
    cost: 0,
    keywords: ['Shield Trigger'],
    effects: [],
    shieldTriggerEffects: [{ type: 'MODIFY_PRIORITY', value: -3, target: 'opponent' }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Shield Trigger: the breaker loses 3 Priority.',
    longDescription: 'Fear grips them when you get too close to the truth about what they saw.',
  },
  {
    id: 'fcp_it_wasnt_me',
    name: "It Wasn't Me",
    cost: 0,
    keywords: ['Shield Trigger'],
    effects: [],
    shieldTriggerEffects: [{ type: 'MODIFY_PATIENCE', value: 3 }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Shield Trigger: restore 3 Patience.',
    longDescription: 'Denial is a shield of its own — they cling to the lie that they were never involved.',
  },
];
