/**
 * Ponder, dev/test cards, and Information Cards (v1.4 §3.9 — colorless,
 * behaviour defined per-encounter via nugget overrides).
 */
import type { CardDefinition } from '../engine';

export const PONDER: CardDefinition = {
  id: 'ponder',
  name: 'Ponder',
  cost: 1,
  keywords: [],
  effects: [{ type: 'DRAW_CARDS', value: 1 }],
  color: 'Colorless',
  supertype: 'Skill',
  subtype: null,
  effectText: 'Draw 1 card.',
  longDescription: 'Some leads need time to breathe before they turn into something useful.',
};

export const DEV_SKILL_CARDS: CardDefinition[] = [
  {
    id: 'dev_push',
    name: 'Push',
    cost: 2,
    keywords: [],
    effects: [{ type: 'BREAK_SHIELDS', target: 'opponent', count: 1 }],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Break 1 Guard Shield.',
    longDescription: "A forceful line of questioning that shatters one of the NPC's defences.",
  },
  {
    id: 'dev_nudge',
    name: 'Nudge',
    cost: 1,
    keywords: [],
    effects: [{ type: 'MODIFY_PATIENCE', value: -1 }],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Pay 1 Patience.',
    longDescription: "A subtle provocation that spends a little of the conversation's goodwill.",
  },
  {
    id: 'dev_hold',
    name: 'Hold Ground',
    cost: 1,
    keywords: ['Safety'],
    effects: [],
    color: 'White',
    supertype: 'Skill',
    subtype: null,
    effectText: 'No effect when played. Safety: breaks as a shield for 0 Patience.',
    longDescription: 'Brace yourself defensively. As a shield, the Safety keyword makes its break cost nothing.',
  },
  {
    id: 'dev_quick_retort',
    name: 'Quick Retort',
    cost: 0,
    keywords: [],
    effects: [{ type: 'MODIFY_PRIORITY', value: 2 }],
    color: 'Red',
    supertype: 'Skill',
    subtype: null,
    effectText: '+2 Priority.',
    longDescription: 'A sharp comeback that seizes back momentum in the conversation.',
  },
];

export const DEV_ENEMY_CARDS: CardDefinition[] = [
  {
    id: 'dev_enemy_dismiss',
    name: 'Dismiss',
    cost: 2,
    keywords: [],
    effects: [{ type: 'BREAK_SHIELDS', target: 'opponent', count: 1 }],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'Break 1 opponent shield.',
    longDescription: 'The NPC dismisses your defences, breaking through one of your shields.',
  },
  {
    id: 'dev_enemy_deflect',
    name: 'Deflect',
    cost: 1,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Skill',
    subtype: null,
    effectText: 'No additional effect.',
    longDescription: 'The NPC deflects your approach, stalling for time.',
  },
];

/**
 * Information Cards. Each is a manifestation of a nugget; encounters override
 * behaviour via nuggetOverrides, otherwise the card converts to Ponder.
 */
export const INFORMATION_CARDS: CardDefinition[] = [
  {
    id: 'info_warehouse_logs',
    name: 'Warehouse Logs',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'warehouse_activity',
    effectText: '???',
    longDescription: 'Shipping manifests from the riverside warehouse. Someone was there after hours.',
  },
  {
    id: 'info_personal_history',
    name: 'Personal History',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'personal_troubles',
    effectText: '???',
    longDescription: 'Court records and old letters. The informant’s troubles are closer to home than they admit.',
  },
  {
    id: 'info_incident_report',
    name: 'Incident Report',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'witnessed_incident',
    effectText: '???',
    longDescription: 'The official report of the incident — with a witness line left conspicuously blank.',
  },
  {
    id: 'info_fan_letters',
    name: 'Bundle of Fan Letters',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'fcp_fan_letters',
    effectText: '???',
    longDescription: 'Hundreds of letters, all unsent. The handwriting deteriorates with each one.',
  },
  {
    id: 'info_idol_schedule',
    name: "Idol's Tour Schedule",
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'fcp_idol_schedule',
    effectText: '???',
    longDescription: 'A tour schedule annotated in two different pens — one of them not the fan’s.',
  },
  {
    id: 'info_passcode',
    name: 'Backstage Passcode',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'fcp_passcode_knowledge',
    effectText: '???',
    longDescription: 'A four-digit code scrawled on a ticket stub. Only staff should know it.',
  },
  {
    id: 'info_physical_traces',
    name: 'Physical Traces',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'fcp_physical_traces',
    effectText: '???',
    longDescription: 'Fibres from a fan-club jacket, found where no fan should ever have stood.',
  },
  {
    id: 'info_witness_statements',
    name: 'Witness Statements',
    cost: 0,
    keywords: [],
    effects: [],
    color: 'Colorless',
    supertype: 'Information',
    subtype: null,
    nuggetId: 'fcp_witness_statements',
    effectText: '???',
    longDescription: 'Three accounts of the same night. All three mention the president of the fan club.',
  },
];
